language: java
jdk: oraclejdk9
services:
  - docker
env:
  - SERVICE_TARGET="cart check"
  - SERVICE_TARGET="user check"
  - REPO_TARGET="order check"
  - REPO_TARGET="cart check"
  - REPO_TARGET="product check"
  - REPO_TARGET="user check"
script:
  - ./gradlew clean jar
  - COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/$SERVICE_TARGET
  - COVERAGE=0.3 ./gradlew -p ./monolithic/repository/$REPO_TARGET

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
#added scheduled build every day

before_deploy:

deploy:
  - echo 'WIP'
